# Generated by Django 2.2 on 2020-11-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrix', '0003_newaltmaterial_newmaterial_newtraditionalmaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newmaterial',
            name='compress',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
        migrations.AlterField(
            model_name='newmaterial',
            name='density',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
        migrations.AlterField(
            model_name='newmaterial',
            name='fracture',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
        migrations.AlterField(
            model_name='newmaterial',
            name='hardness',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
        migrations.AlterField(
            model_name='newmaterial',
            name='uts',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
        migrations.AlterField(
            model_name='newmaterial',
            name='youngs',
            field=models.CharField(default='NoneYetFound', max_length=15),
        ),
    ]
